import "@/styles/globals.css";
import { type FC } from "react";

interface RootLayoutProps {
  children: React.ReactNode;
}

export const metadata = {
  description: "Generated by create next app",
  title: "Sample",
};

const RootLayout: FC<RootLayoutProps> = (props) => {
  return (
    <html lang="ja">
      <body className="">{props.children}</body>
    </html>
  );
};

export default RootLayout;
